sudo: required
language: java
jdk: openjdk8
services: docker

before_install: docker pull nfcore/rnaseq:latest

install:
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install nf-core/tools
  - git clone https://github.com/nf-core/tools.git /tmp/nf-core-tools
  - cd /tmp/nf-core-tools
  - pip install --user -e .
  # Make test directories
  - mkdir ${TRAVIS_BUILD_DIR}/tests
  - cd ${TRAVIS_BUILD_DIR}/tests


env:
  - NXF_VER=0.30.1
  - ''

script:
  # Lint the pipeline code
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  # Run, build reference genome with STAR
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker
  # Run, build reference genome with HISAT2
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker --aligner hisat2
