sudo: required
language: python
services: docker
cache: pip
jdk: openjdk8

matrix:
  fast_finish: true
  include:
  - name: "Minimum Nextflow version, regular test suite"
    env: NXF_VER='0.32.0' SUITE=test
  - name: "Latest Nextflow version, regular test suite"
    env: NXF_VER='' SUITE=test_gz
  - name: "Latest Nextflow version, gzipped references"
    env: NXF_VER='' SUITE=test_gz
  - name: "Lint the pipeline code"
    script: nf-core lint ${TRAVIS_BUILD_DIR}
    python: '3.6'
    env: NXF_VER='0.32.0'
  - name: "Lint the documentation"
    script: markdownlint ${TRAVIS_BUILD_DIR} -c ${TRAVIS_BUILD_DIR}/.github/markdownlint.yml
    python: '3.6'

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && [ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ])'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull nfcore/rnaseq:dev
  # Fake the tag locally so that the pipeline runs properly
  # Looks weird when this is :dev to :dev, but makes sense when testing code for a release (:dev to :1.0.1)
  - docker tag nfcore/rnaseq:dev nfcore/rnaseq:dev

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install nf-core/tools
  - pip install --upgrade pip
  - pip install nf-core
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli

script:
  # Lint the pipeline code
  - nf-core lint ${TRAVIS_BUILD_DIR}
  # Lint the documentation
  - markdownlint ${TRAVIS_BUILD_DIR} -c ${TRAVIS_BUILD_DIR}/.github/markdownlint.yml
  # Run with STAR
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker
  # Run with HISAT2
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker --aligner hisat2
  # Run with STAR and Salmon
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker --pseudo_aligner salmon
  # Run with Salmon and no alignment
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker --pseudo_aligner salmon --skipAlignment
  # Additional gzipped-only things that are only invoked if $SUITE=test_gz
  - ./test-gzipped-star-hisat2-indices.sh
