# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-1.4dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - trim-galore=0.6.2
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - hisat2=2.1.0
  - picard=2.20.0
  - bioconductor-dupradar=1.14.0
  - conda-forge::r-data.table=1.12.2
  - conda-forge::r-gplots=3.0.1.1
  - bioconductor-edger=3.24.3
  - bioconductor-tximeta=1.0.3
  - bioconductor-summarizedexperiment=1.12.0
  - conda-forge::r-markdown=0.9
  - csvtk=0.17.0
  - qualimap=2.2.2b
  - preseq=2.0.3
  - rseqc=3.0.0
  - rsem=1.3.2
  - samtools=1.9
  - salmon=0.14.0
  - stringtie=1.3.6
  - subread=1.6.4
  - gffread=0.9.12
  - deeptools=3.2.1
  - multiqc=1.7
  - matplotlib=3.0.3
  - r-base=3.5.1
