# Config file for Python. Mostly used to configure linting of bin/*.py with Ruff.
# Should be kept the same as nf-core/tools to avoid fighting with template synchronisation.
[tool.ruff]
line-length = 120
target-version = "py38"
select = ["I", "E1", "E4", "E7", "E9", "F", "UP", "N"]
cache-dir = "~/.cache/ruff"

[tool.ruff.isort]
known-first-party = ["nf_core"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]
