channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.4.2
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-rcolorbrewer=1.1_3
  - conda-forge::r-pheatmap=1.0.12
  - bioconda::bioconductor-deseq2=1.46.0
  - bioconda::bioconductor-biocparallel=1.40.0
  - bioconda::bioconductor-tximport=1.34.0
  - bioconda::bioconductor-complexheatmap=2.22.0
