contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaseq channel"
    url: https://nfcore.slack.com/channels/rnaseq
    about: Discussion about the nf-core/rnaseq pipeline
