name: nf-core AWS test
# This workflow is triggered on PRs to the master branch.
# It runs the -profile 'test' on AWS batch

on:
  push:
    branches:
      - master
      - dev # just for testing purposes, to be removed
  release:
    types: [published]

jobs:
  run-awstest:
    if: github.repository == 'nf-core/rnaseq'
    name: Run AWS test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Install awscli
        run: conda install -c conda-forge awscli
      - name: Start AWS batch job
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_KEY_SECRET}}
          TOWER_ACCESS_TOKEN: ${{secrets.TOWER_ACCESS_TOKEN}}
        run: |
          aws batch submit-job \
            --region eu-west-1 \
            --job-name nf-core-rnaseq \
            --job-queue 'default-8b3836e0-5eda-11ea-96e5-0a2c3f6a2a32' \
            --job-definition nextflow \
            --container-overrides '{"command": ["nf-core/rnaseq", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://nf-core-awsmegatests/rnaseq/results-'"${GITHUB_SHA}"' -w s3://nf-core-awsmegatests/rnaseq/work-'"${GITHUB_SHA}"' -with-tower"], "environment": [{"name": "TOWER_ACCESS_TOKEN", "value": "'"$TOWER_ACCESS_TOKEN"'"}]}'
