name: nf-core AWS test
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.
# It runs the -profile 'test' on AWS batch

on:
  workflow_dispatch:
jobs:
  run-platform:
    name: Run AWS tests
    if: github.repository == 'nf-core/rnaseq'
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Seqera Platform CLI tool action
      - name: Launch workflow via Seqera Platform
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ vars.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ vars.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ vars.AWS_S3_BUCKET }}/work/rnaseq/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ vars.AWS_S3_BUCKET }}/rnaseq/results-test-${{ github.sha }}"
            }
          profiles: test

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: Seqera Platform debug log file
          path: |
            tower_action_*.log
            tower_action_*.json
