name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  submit-test-full-to-tower:
    strategy:
      matrix:
        compute-environment:
          - name: AWS
            outdir: ${{ secrets.TOWER_BUCKET_AWS }}/results/${{ github.sha }}
            workdir: ${{ secrets.TOWER_BUCKET_AWS }}/work/${{ github.sha }}
            compute_env: ${{ secrets.TOWER_CE_AWS_CPU }}
            profile: test
          - name: GCP
            outdir: ${{ secrets.TOWER_BUCKET_GCP }}/results/${{ github.sha }}
            workdir: ${{ secrets.TOWER_BUCKET_GCP }}/work/${{ github.sha }}
            compute_env: ${{ secrets.TOWER_CE_GCP_CPU }}
            profile: test
          - name: AZ
            outdir: ${{ secrets.TOWER_BUCKET_AZ }}/results/${{ github.sha }}
            workdir: ${{ secrets.TOWER_BUCKET_AZ }}/work/${{ github.sha }}
            compute_env: ${{ secrets.TOWER_CE_AZURE_CPU }}
            profile: test
    runs-on: ubuntu-latest
    steps:
      - uses: seqeralabs/action-tower-launch@v1
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ matrix.compute-environment.compute_env }}
          workdir: ${{ matrix.compute-environment.workdir }}
          run_name: ${{ matrix.compute-environment.name }}_${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
          wait: false
          parameters: |
            {
                "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
                "outdir": "${{ matrix.compute-environment.outdir }}"
            }
          profiles: ${{ matrix.compute-environment.profile }}
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: tower_action_*.log
